

import React from 'react'
import { motion } from 'framer-motion'
import { BrainCircuit, Sparkles } from 'lucide-react'

interface SummaryCardProps {
  summary: string
}

/**
 * Displays the AI-generated resume summary. Visually matches
 * ATSScoreCard (same card shell, palette, shadow, and animation
 * language) so the two sit naturally side by side in the analysis view.
 */
const SummaryCard: React.FC<SummaryCardProps> = ({ summary }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ y: -4, scale: 1.005 }}
      transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
      className="flex w-full flex-col rounded-2xl border border-[#5C4033]/8 bg-white p-8 shadow-[0_8px_28px_rgba(92,64,51,0.08)] transition-shadow duration-300 hover:shadow-[0_18px_42px_rgba(92,64,51,0.14)] sm:p-10"
      style={{ fontFamily: 'Inter, sans-serif' }}
    >
      {/* Top row: icon + title */}
      <div className="flex items-center gap-3">
        <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#C89B3C]/10 text-[#C89B3C]">
          <BrainCircuit className="h-5 w-5" strokeWidth={1.8} />
        </div>
        <h3 className="text-lg font-semibold text-[#5C4033] sm:text-xl">
          AI Resume Summary
        </h3>
      </div>

      {/* Summary text */}
      <p className="mt-5 max-w-2xl text-base leading-relaxed text-[#5C4033]/90">
        {summary}
      </p>

      {/* Bottom-right badge */}
      <div className="mt-6 flex justify-end">
        <span className="flex items-center gap-1.5 rounded-full bg-[#FAF7F2] px-3 py-1.5 text-xs font-semibold text-[#8A7A6C]">
          <Sparkles className="h-3.5 w-3.5 text-[#C89B3C]" strokeWidth={1.8} />
          Generated by AI
        </span>
      </div>
    </motion.div>
  )
}

export default SummaryCard